Repository QUB-ASL/bzzz, pull requests merged in 2023-08, with the labels that each got.

#91 Added new schematics with updated mounting holes
  README.md
  design/PCBs/SENSOR_BOARD_V2/SCHEMATICS/Sensor board layout image.png
  design/PCBs/SENSOR_BOARD_V2/SCHEMATICS/Sensor board schematic image.png
  design/PCBs/SENSOR_BOARD_V2/SCHEMATICS/Sensor board v5.fbrd
  design/PCBs/SENSOR_BOARD_V2/SCHEMATICS/Sensor board v6.fsch
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/Assembly/PnP_Sensor board v7_back.txt
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/Assembly/PnP_Sensor board v7_front.txt
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/Assembly/Sensor board v7.txt
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/DrillFiles/drill_1_16.xln
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/copper_bottom.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/copper_top.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/gerber_job.gbrjob
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/profile.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/silkscreen_bottom.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/silkscreen_top.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/soldermask_bottom.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/soldermask_top.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/solderpaste_bottom.gbr
  design/PCBs/SENSOR_BOARD_V3/MANUFACTURING FILES/GerberFiles/solderpaste_top.gbr
  design/PCBs/SENSOR_BOARD_V3/SCHEMATICS/Sensor board layout picture.png
  design/PCBs/SENSOR_BOARD_V3/SCHEMATICS/Sensor board v6.fsch
  design/PCBs/SENSOR_BOARD_V3/SCHEMATICS/Sensor board v8.fbrd
Labels: docs, hardware

#98 fixed small typo in main.cpp
  src/main.cpp
Labels: bug, esp32

#114 Update SAFETY.md
  SAFETY.md
Labels: docs

#113 Hotfix of logging system
  raspberry/data/README.md
  raspberry/main.py
Labels: bug, docs, python, pi
