Repository QUB-ASL/bzzz, pull requests merged in 2023-05, with the labels that each got.

#16 Integration of individual components
  hardware/tests/hw_test_ahrs.cpp
  include/ahrs.hpp
  include/config.hpp
  include/controller.hpp
  include/motors.hpp
  include/quaternion.hpp
  include/radio.hpp
  src/ahrs.cpp
  src/controller.cpp
  src/main.cpp
  src/motors.cpp
  src/quaternion.cpp
  src/radio.cpp
Labels: feature, esp32

#27 Release of first working version
  .gitignore
  CONTRIBUTING.md
  hardware/tests/hw_test_ahrs.cpp
  hardware/tests/hw_test_motors.cpp
  include/ahrs.hpp
  include/config.hpp
  include/controller.hpp
  include/imu.hpp
  include/motors.hpp
  include/quaternion.hpp
  include/radio.hpp
  platformio.ini
  raspberry/read_sbus/README.md
  raspberry/read_sbus/hw_test_receiver.py
  raspberry/read_sbus/read_sbus_from_GPIO.py
  raspberry/read_sbus/read_sbus_from_GPIO_receiver.py
  src/ahrs.cpp
  src/config.cpp
  src/controller.cpp
  src/imu.cpp
  src/main.cpp
  src/motors.cpp
  src/quaternion.cpp
  src/radio.cpp
Labels: esp32

#32 Implementation of fail-safes
  include/config.hpp
  include/radio.hpp
  src/main.cpp
  src/radio.cpp
Labels: feature, esp32

#35 Update README.md (project description and demo)
  README.md
Labels: docs

#44 Initial angular velocities
  src/main.cpp
Labels: feature, esp32

#45 Refactoring
  include/ahrs.hpp
  include/config.hpp
  include/motors.hpp
  include/radio.hpp
  include/util.hpp
  platformio.ini
  src/ahrs.cpp
  src/config.cpp
  src/main.cpp
  src/motors.cpp
  src/radio.cpp
  src/util.cpp
Labels: feature, esp32

#34 Safety instructions (SAFETY.md)
  SAFETY.md
Labels: docs
